config/routes.rb
Rails.application.routes.draw do
  resources :agents
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create index]

  resources :campaigns do
    resources :forms, only: %i[new create edit] do
      resources :questions, only: %i[new create]
    end


    resources :leads, except: %i[new create]
  end

  get ':campaign_name/:form_name', to: 'leads#new', as: :campaign_form

  resources :leads, only: [] do
    resources :response, only: %i[new create]
  end

  resources :forms do
   resources :leads
  end

  resources :responses, only: %i[create] do
    resources :answers, only: %i[new create] do
      collection do
        post 'attempt'
      end
    end
  end

  resources :responses, only: %i[edit update]
  resources :forms, only: [] do
    resources :questions, only: %i[] do
      resources :form_questions, only: [:create]
    end
  end

  resources :questions, only: [] do
    resources :options, only: %i[:create]
    # resources :options, only: %i[new create]
  end

  resources :forms, only: :update

  get "dashboard", to: "pages#dashboard"
  get "thankyou", to: "pages#thankyou"
  post "sendemail", to: "send_email#send_email", as: "send_email"
  post "sendindividualemail", to: "send_email#send_individual_email", as: "send_individual_email"
end

app/models/lead.rb
class Lead < ApplicationRecord
  has_one :response
  has_many :answers, through: :responses

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true

  # after_create :analyse_sentiment

  # def analyse_sentiment(response)
  #   answers = response.answers
  #   rating = 0.0
  #   answers.each do |answer|
  #     # if multiple choice, take hard coded sentiment points
  #     if answer.question.format == "multiple choice"
  #       answer.question.options.each do |option|
  #         if option.value == answer.value
  #           sentiment = option.sentiment_value
  #           rating += sentiment
  #         end
  #       end
  #     else
  #       # else, take value from chatgpt analysis
  #       value = answer.sentiment_value
  #       rating += value
  #     end
  #   end
  #   # # calculate the average / total rating
  #   final_rating = rating / anwers.length

  #   # attribute rating to leads > rating
  #   this.rating = final_rating

  #   # self.rating = 2
  #   # save!
  # end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  after_action :allow_iframe
  before_action :set_leads, only: %i[show]

  def index
    @leads = Campaign.find(params[:campaign_id]).leads.order(rating: :desc)

    @leads = @leads.where("title ILIKE ?", "%#{params[:query]}%") if params[:query].present?

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "leads/show", locals: { leads: @leads }, formats: [:html] }
    end
  end

  def new
    @campaign = Campaign.find_by(name: params[:campaign_name])
    @form = Form.find_by(title: params[:form_name], campaign: @campaign)
    @lead = Lead.new
  end

  def create
    @form = Form.find(params[:form_id])
    @lead = Lead.new(leads_params)

    if @lead.save
      @response = Response.create(form: @form, lead: @lead)

      redirect_to edit_response_path(@response)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def message

  end

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

  def set_leads
    @lead = Lead.find(params[:id])
  end

  def leads_params
    params.require(:lead).permit(:name, :email, :phone_number)
  end
end

app/views/leads/_lead.html.erb
<div data-controller="popup individual-email">
	<div class="row g-2">

		<div class="col-1">
			<div class="p-2 t-1">
				<% if lead.rating > 6.66 %>
					<i class="fa-solid fa-star text-primary"></i>
				<% elsif lead.rating > 3.33 %>
					<i class="fa-regular fa-star-half-stroke text-primary"></i>
				<% else %>
					<i class="fa-regular fa-star text-primary"></i>
				<% end %>
			</div>
		</div>

		<div class="col-3">
			<div class="p-2 mt-1">
				<a class="text-primary text-decoration-none popup-link" data-action="click->popup#show"><%= lead.name %></a>
			</div>
		</div>

		<div class="col-4">
			<div class="p-2 mt-1"><%= lead.email%></div>
		</div>

		<div class="col-3">
			<div class="p-2 t-1"><%= lead.phone_number%></div>
		</div>

		<div class="col-1">
			<div class="p-2 toggler-wrapper style-2">
				<%# Need to change lead.email to index later on when we time - Sabrina %>
				<%= f.check_box "email#{lead.id}", {:class => "myclass", :id => lead.name}, lead.id, "" %>
			</div>
		</div>

	</div>



	<%= popup title: lead.name do %>
		<div class="d-flex justify-content-between pt-3">
      <h3 class="indiv-font">Email:</h3>
      <div class="px-1 box overflow-auto email-box email-field">
        <%= lead.email %>
      </div>

      <h3 class="indiv-font">Phone No:</h3>
      <div class="px-1 box phone-number-box">
        <%= lead.phone_number %>
      </div>
    </div>

		<ul class="nav nav-tabs mt-4" id="myTab<%= lead.id %>" role="tablist">
			<li class="nav-item" role="presentation">
				<button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane-<%= lead.id %>" type="button" role="tab" aria-controls="home-tab-pane-<%= lead.id %>" aria-selected="true">Response</button>
			</li>
			<li class="nav-item" role="presentation">
				<button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane-<%= lead.id %>" type="button" role="tab" aria-controls="profile-tab-pane-<%= lead.id %>" aria-selected="false">Message</button>
			</li>
		</ul>
		<div class="tab-content mt-2" id="myTabContent<%= lead.id %>">

			<div class="tab-pane fade show active" id="home-tab-pane-<%= lead.id %>" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
				<div class="box overflow-auto response-size">
      <div class="m-4">
        <% UserQuestion.join_questions_for(current_user).each_with_index do |question, index| %>
          <hr>
          <p class="text-primary"> <%= question.title %></p>
          <hr>
          <%= lead.response.answers[index].value %>
          <%# lead.response.answers.each do |answer| %>
            <%# <p>= answer.value</p> %>
          <%# end %>
        <% end %>
					</div>
				</div>
				<h3 class="indiv-font pt-3">Rating</h3>
				<div class="p-1">
					<% if lead.rating > 6.66 %>
						<i class="mx-2 fa-regular fa-star text-lighter fa-xl"></i>
						<i class="mx-2 fa-regular fa-star-half-stroke text-lighter fa-xl"></i>
						<i class="mx-2 fa-solid fa-star color-hot fa-xl"></i>
					<% elsif lead.rating > 3.33 %>
						<i class="mx-2 fa-regular fa-star text-lighter fa-xl"></i>
						<i class="mx-2 fa-regular fa-star-half-stroke color-warm fa-xl"></i>
						<i class="mx-2 fa-solid fa-star text-lighter fa-xl"></i>
					<% else %>
						<i class="mx-2 fa-regular fa-star color-cold fa-xl"></i>
						<i class="mx-2 fa-regular fa-star-half-stroke text-lighter fa-xl"></i>
						<i class="mx-2  fa-solid fa-star text-lighter fa-xl"></i>
					<% end %>
				</div>
			</div>

			<div class="tab-pane fade" id="profile-tab-pane-<%= lead.id %>" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
				<textarea id="message_box_<%= lead.id %>" maxlength="350" class="box overflow-auto message-box-size" data-individual-email-target="message"></textarea>
				<div class="my-4 d-flex flex-row-reverse">
					<%= button_to "Message", send_individual_email_path(lead_id: lead.id, lead_email: lead.email, lead_name: lead.name), remote: true, params: { message: "Thanks for your enquiry, when are you free for a chat?" }, class: "btn btn-primary message-box", data: { turbo_frame: "popup-frame" }, id: "send-message-button" %>
				</div>
			</div>
		</div>
  <% end %>
</div>

<script>
	document.querySelector("#message_box_<%= lead.id %>").addEventListener("keyup", (e) => {
		console.log(e.currentTarget.value);
		const emailMail = document.getElementsByClassName('email-field')[<%= lead.id - 1 %>];
		console.log(emailMail.innerHTML)
		document.querySelector("#profile-tab-pane-<%= lead.id %>").querySelector("input[name='message']").value = e.currentTarget.value
	});
</script>

app/views/leads/index.html.erb
<%= form_with url: send_email_path, method: :post do |f| %>
<div data-controller="popup">
  <div class="container">
    <div class="row">
      <h1 class="text-center my-5">Leads</h1>

      <div class="d-flex col-auto my-3">
        <i class="fa-solid fa-magnifying-glass p-2 m-1 opacity-25"></i>
        <div data-controller="search-leads shadow-sm" style="width: 1000px;">
          <%= form_with url: campaign_leads_path, method: :get, html: {class:
            "mb-4", data: {search_leads_target: "form"}} do |f| %>
            <%= f.text_field :query,
                            class: "form-control",
                            placeholder: "Search...",
                            value: params[:query],
                            data:
                            {search_leads_target: "input",
                              action: "keyup->search-leads#update"
                          } %>
          <% end %>
                <%# <%= render "show", leads: @leads %>
        </div>
      </div>

      <div class="container mt-1">
        <div class="row g-2">

          <div class="col-1">
            <div class="p-2 fs-5">No.</div>
          </div>

          <div class="col-3">
            <div class="p-2 fs-5">Name</div>
          </div>

          <div class="col-4">
            <div class="p-2 fs-5">Email</div>
          </div>

          <div class="col-3">
            <div class="p-2 fs-5">Phone No.</div>
          </div>
        </div>
      </div>

      <div class="box overflow-auto p-3 shadow-sm box-height">

          <%= render @leads, f: f %>
      </div>
    </div>
  </div>

  <div class="mt-4 text-center">
    <button type="button" class="btn btn-primary bottom-buttons text-decoration-none popup-link" data-action="click->popup#show">Message Leads</button>
  </div>

  <%= popup title: "New Message" do %>
    <p class="opacity-50 mt-5">Input Message to clients here:</p>
      <%# <textarea class="new-message-box box overflow-auto p-3" placeholder="Write Message Here!"></textarea> %>
      <textarea class="new-message-box box overflow-auto p-3" name="textarea" placeholder="Write Message Here!"></textarea>
    <div class="my-4 message-right">
      <%# <%= button_to "Message", send_email_path(), class: "btn btn-primary message-box" %>
      <%# <%= link_to "Message", send_email_path, class: "btn btn-primary message-box" %> 
			<button class="btn btn-primary message-box" type="submit">Message</button>
		</div>
  <% end %>
</div>
<% end %>

app/views/leads/new.html.erb
<div class="container">
  <h1><%= @form.title %></h1>
    <%# <div class="my-5 w-70"> %>
      <%= simple_form_for([@form, @lead]) do |f| %>
        <%= f.input :name %>
        <%= f.input :email %>
        <%= f.input :phone_number %>
        <%= f.submit value: "Next", class: "btn btn-primary"%>
      <% end %>
  </div>
</div>