config/routes.rb
Rails.application.routes.draw do
  resources :agents
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create index]

  resources :campaigns do
    resources :forms, only: %i[new create edit] do
      resources :questions, only: %i[new create]
    end


    resources :leads, except: %i[new create]
  end

  get ':campaign_name/:form_name', to: 'leads#new', as: :campaign_form

  resources :leads, only: [] do
    resources :response, only: %i[new create]
  end

  resources :forms do
   resources :leads
  end

  resources :responses, only: %i[create] do
    resources :answers, only: %i[new create] do
      collection do
        post 'attempt'
      end
    end
  end

  resources :responses, only: %i[edit update]
  resources :forms, only: [] do
    resources :questions, only: %i[] do
      resources :form_questions, only: [:create]
    end
  end

  resources :questions, only: [] do
    resources :options, only: %i[:create]
    # resources :options, only: %i[new create]
  end

  resources :forms, only: :update

  get "dashboard", to: "pages#dashboard"
  get "thankyou", to: "pages#thankyou"
  post "sendemail", to: "send_email#send_email", as: "send_email"
  post "sendindividualemail", to: "send_email#send_individual_email", as: "send_individual_email"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def new
    @form = Form.new
    @campaign = Campaign.find(params[:campaign_id])
  end

  def create
    @form = Form.new(form_params)
    @campaign = Campaign.find(params[:campaign_id])
    @question = Question.new
    @form_question = FormQuestion.new
    @user_questions = current_user.user_questions
    @user_questions.each do |user_question|
      @form.questions << user_question.question if user_question.compulsory
    end
    @form_question.form = @form
    @form.campaign = @campaign
    @campaign.user = current_user

    if @form.save
      redirect_to edit_campaign_form_path(@campaign, @form)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @campaign = Campaign.find_by(name: params[:campaign_name])
    @form = Form.find_by(title:params[:form_name])
  end

  def edit
    @question = Question.new

    @form = Form.find(params[:id])
    @lead = Lead.new
    @campaign = Campaign.find(params[:campaign_id])
    @previous_questions = UserQuestion.non_compulsory_questions_for(current_user) - @form.questions

    @options = @previous_questions.map { |compulsory| { value: compulsory.id, text: compulsory.title }}
  end

  def update
    if params.dig("form", "questions").present?
      questionids = params.dig("form", "questions").split(",")
      questions = Question.where(id: questionids)
      @form = Form.find(params[:id])
      @form.questions << questions
    end

    # render json: { msdg: questionids }
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.json do
        render json: {
          questions_partial: render_to_string(partial: "question_list", locals: { questions: }, formats: [:html])
        }
      end
    end
  end

  def sentiment
    # retrieve the answer
    @response = Response.find(params[:response_id])
    @form = Form.find(params[:id])
    form_questions = @form.questions
    answers = []
    answers = form_questions.map do |question|
      answer = question.answers.find { |answer| }
      answers << answer
    end
    questions_list = []
    replies_list = []
    # retrieve the question from the answer (Only take open-ended qns)
    answers.each do |answer|
      next if answer.question.format == "multiple choice"

      reply = answer.value
      replies_list << reply
      question = answer.question.title
      questions_list << question
    end
    # use chatgpt > give it the question & answer and ask for sentiment
    content = "
    Based on these questions: #{questions_list} and these answers: #{replies_list}, give me your opinions on the sentiments of the answers and return an array of floats from 0 - 10,
    (with 0 being the most negative and 10 being the most positive). The array of questions is related to their array of answers based on their index.
    Format your answer in an array of floats, showing just the sentiment value of the answers. nothing else"
    client = OpenAI::Client.new(access_token: ENV['OPENAI_TOKEN'])
    response = client.chat(
      parameters: {
        temperature: 1.0,
        model: 'gpt-3.5-turbo',
        messages: [
          { role: 'user',
            content: content
          }
        ]
      }
    )
    reply = response.dig('choices', 0, 'message', 'content')
    puts reply
    # return float
    # attribute value to answers > sentiment_value
    answers.each_with_index do |answer, index|
      next if answer.blank?

      single_answer = Answer.find_by(value: answer)
      single_answer&.update(sentiment_value: reply[index] || 0.0)
    end
  end


  # def sentiment_draft
  #   # retrieve the answer
  #   @form = Form.find(params[:id])
  #   form_questions = @form.questions
  #   answers = []
  #   form_questions.each do |question|
  #     answer = question.answer
  #     answers << answer
  #   end
  #   questions_list = []
  #   replies_list = []
  #   # retrieve the question from the answer (Only take open-ended qns)
  #   answers.each do |answer|
  #     next if answer.question.format == "multiple choice"

  #     reply = answer.value
  #     replies_list << reply
  #     question = answer.question.title
  #     questions_list << question
  #   end
  #   # use chatgpt > give it the question & answer and ask for sentiment
  #   content = "
  #   Based on these questions: #{questions_list} and these answers: #{replies_list}, give me your opinions on the sentiments of the answers and return an array of floats from 0 - 10,
  #   (with 0 being the most negative and 10 being the most positive). The array of questions is related to their array of answers based on their index.
  #   Format your answer in an array of floats, showing just the sentiment value of the answers. nothing else"
  #   client = OpenAI::Client.new(access_token: ENV['OPENAI_TOKEN'])
  #   response = client.chat(
  #     parameters: {
  #       temperature: 1.0,
  #       model: 'gpt-3.5-turbo',
  #       messages: [
  #         { role: 'user',
  #           content: content
  #         }
  #       ]
  #     }
  #   )
  #   reply = response.dig('choices', 0, 'message', 'content')
  #   puts reply
  #   # return float
  #   # attribute value to answers > sentiment_value
  #   answers.each_with_index do |answer, index|
  #     next if answer.blank?

  #     single_answer = Answer.find_by(value: answer)
  #     single_answer&.update(sentiment_value: reply[index] || 0.0)
  #   end
  # end

  private

  def form_params
    params.require(:form).permit(:title)
  end
end

app/views/forms/_create_new_multiple_choice.html.erb
<%= popup title: "Add your customized question (MCQ)" do %>
  <%# Form for question %>
  <%= simple_form_for question, url: campaign_form_questions_path(campaign, form) do |f| %>
    <%= f.input :format, as: :hidden, input_html: { value: 'multiple choice' } %>
    <h5> Please provide a rating between 1 and 10 for each option, where 1 indicates a lower rating and 10 indicates a higher rating.</h5>
    <br>
    <%= f.input :title, label: "Type your question here" %>

    <div data-controller="add-question-option">
      <div data-add-question-option-target="optionsList" id="options"></div>
      <button type="button" class="btn btn-primary" id="add-option-btn" data-action="click->add-question-option#addOption">Add Option</button>
    </div>
    <br>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/forms/_create_new_qn.html.erb
<%= popup title: "Add your customized question" do %>
  <%# Form for question %>
  <%= simple_form_for question, url: campaign_form_questions_path(campaign, form) do |f| %>
    <%= f.input :format, as: :hidden, input_html: { value: 'Open-Ended' } %>
    <%= f.input :title, label: "Type your question here" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/forms/_question_list.html.erb
<% questions.each do |question| %>
  <div class="mb-3 string required disabled lead_name">
    <label data-choose-previous-questions-target="addqn" class="form-label string required disabled" for="lead_name">
    <%= question.title %><abbr title="required">*
    </abbr></label>
    <input class="delete-checkbox" type="checkbox">
    <input class="form-control string required disabled default-value" value="Lead will input answer here" disabled="disabled" type="text" name="lead[name]" id="lead_name">
  </div>
<% end %>

app/views/forms/edit.html.erb
<div class="container" data-controller="choose-previous-questions">
  <div class="row">
    <h1 class="text-center my-5">Customize Your Form Questions</h1>

      <%# Lead questions %>
      <%= simple_form_for [@campaign, @lead] do |f| %>
        <%= f.input :name, disabled: true, input_html: { value: 'Lead will input name here', class: 'default-value' } %>
        <%= f.input :email, disabled: true, input_html: { value: 'Lead will input email here', class: 'default-value' }  %>
        <%= f.input :phone_number, disabled: true, input_html: { value: 'Lead will input phone number here', class: 'default-value' }  %>
      <% end %>

      <%# Current_user compulsory questions %>
      <%# <h2>Previously saved questions</h2> %>


      <div data-choose-previous-questions-target='addqn'>
        <%# additional questions %>
        <% @form.questions.each do |question| %>
          <div class="mb-3 string required disabled lead_name">
            <label data-choose-previous-questions-target="addqn" class="form-label string required disabled" for="lead_name">
            <%= question.title %> <abbr title="required">*</abbr>
            <% if question.is_mcq? %>
              <br><small>
              <br>
              <p><strong>Options:</strong></p>
                <% question.options.each do |option| %>
                  <%= option.value %> <br>
                <% end %>
              </small>
            <%end%>
            </abbr></label>
            <%# <input class="delete-checkbox" type="checkbox"> %>
            <input class="form-control string required disabled default-value" value="Lead will input answer here" disabled="disabled" type="text" name="lead[name]" id="lead_name">
          </div>
        <% end %>
      </div>

    <div>
      <p><strong>Add custom questions to your form (optional)</strong></p>
        <% unless @previous_questions.empty? %>
          <div class="rounded form-control default-value" data-action="click->choose-previous-questions#popupQuestions">
            Frequently asked questions:
            <%= simple_form_for @form, remote: true, data: {
                choose_previous_questions_target: "form"
              } do |f| %>
              <%= f.input :questions,
              input_html: {
                id: "tom-select-it",
                data: {
                  controller: 'tom-select',
                  tom_select_options_value: @options
                }
              },
              data: {
                choose_previous_questions_target: "tom"
              } %>
            <% end %>
            <%# <input data-choose-previous-questions-target="tom" id="tom-select-it" /> %>
            <div>
              <%= button_tag 'Add', class: 'btn btn-info', 'data-action': 'click->choose-previous-questions#submitQuestions' %>
            </div>
          </div>
        <% end %>

      <div class="form-control default-value">
        <div>
          <p>Select the format of the question:</p>
        </div>
        <span data-controller="popup">
          <%= button_tag 'Open-Ended', class: 'btn btn-info', 'data-action': 'click->popup#show' %>
          <%= render 'create_new_qn', form: @form, question: Question.new, campaign: @campaign %>
        </span>
        <span data-controller="popup">
          <%= button_tag 'Multiple Choice', class: 'btn btn-info', 'data-action': 'click->popup#show' %>
          <%= render 'create_new_multiple_choice', form: @form, question: @question, campaign: @campaign %>
        </span>
      </div>
    </div>

      <%#= f.submit "Submit new form!", class: "btn btn-primary" %>
      <div class="flex-container my-3">
      <%= link_to 'Generate Lead Form URL', campaigns_path, class: "btn btn-primary" %>
      <%= link_to "Back to edit Form Title", new_campaign_form_path(@campaign), class: "btn btn-secondary" %>
      </div>
  </div>

      <%# <script>
        // Retrieve the link element
        const randomLink = document.getElementById('randomLink');

        // Event listener for link click
        randomLink.addEventListener('click', (event) => {
          // Prevent the default behavior of the link
          event.preventDefault();

          // Generate a random URL
          const randomURL = generateRandomURL();

          // Open the random URL in a new tab or window
          window.open(randomURL, '_blank');
        });

        // Function to generate a random URL
        function generateRandomURL() {
          // Replace "form.html" with the actual file name and extension of your form
          const formURL = "https://leadspro-9ddc3d1f2886.herokuapp.com/forms/4/leads/new";

          // Generate a random query parameter or value
          const randomParam = Math.random().toString(36).substring(7);

          // Combine the form URL with the random query parameter
          return `${formURL}?id=${randomParam}`;
        }
      </script> %>
</div>

app/views/forms/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center my-5">Create a form</h1>
      <%= simple_form_for [@campaign, @form] do |f| %>
        <%= f.input :title %>
        <%= f.submit "Proceed to Form creation", class: "btn btn-primary" %>
        <%= link_to "Back to Edit campaign", new_campaign_path, class: "btn btn-secondary" %>
      <% end %>

  </div>
</div>

app/views/forms/show.html.erb
<div class="container">
  <h1><%= @form.title %></h1>
    <%# <div class="my-5 w-70"> %>
  <%= simple_form_for([@form, @lead]) do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
  <%# </div> %>
</div>