config/routes.rb
Rails.application.routes.draw do
  resources :agents
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create index]

  resources :campaigns do
    resources :forms, only: %i[new create edit] do
      resources :questions, only: %i[new create]
    end


    resources :leads, except: %i[new create]
  end

  get ':campaign_name/:form_name', to: 'leads#new', as: :campaign_form

  resources :leads, only: [] do
    resources :response, only: %i[new create]
  end

  resources :forms do
   resources :leads
  end

  resources :responses, only: %i[create] do
    resources :answers, only: %i[new create] do
      collection do
        post 'attempt'
      end
    end
  end

  resources :responses, only: %i[edit update]
  resources :forms, only: [] do
    resources :questions, only: %i[] do
      resources :form_questions, only: [:create]
    end
  end

  resources :questions, only: [] do
    resources :options, only: %i[:create]
    # resources :options, only: %i[new create]
  end

  resources :forms, only: :update

  get "dashboard", to: "pages#dashboard"
  get "thankyou", to: "pages#thankyou"
  post "sendemail", to: "send_email#send_email", as: "send_email"
  post "sendindividualemail", to: "send_email#send_individual_email", as: "send_individual_email"
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user, dependent: :destroy

  has_many :forms, dependent: :destroy
  has_many :responses, through: :forms
  has_many :leads, through: :responses

  validates :name, presence: true, uniqueness: true
  validates :details, presence: true
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update]

  def index
    @campaigns = Campaign.all

    @campaigns = @campaigns.where("title ILIKE ?", "%#{params[:query]}%") if params[:query].present?

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "campaigns/show", locals: { campaigns: @campaigns }, formats: [:html] }
    end
  end

  def new
    @campaign = Campaign.new
    @campaign.user = current_user
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user
    @campaign.date_created = Time.now

    if @campaign.save
      redirect_to new_campaign_form_path(@campaign)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: "Campaign updated successfully."
    else
      render :edit
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:name, :start_date, :end_date, :details)
  end
end

app/views/campaigns/_campaign.html.erb
<div class="col-12">
  <% campaigns.each do |campaign| %>
    <div class="row g-2 pt-2" data-controller="popup">
      <div class="col-3">
        <div class="p-2 mt-1 text-dark text-decoration-none"><%= link_to campaign.name, campaign_leads_path(campaign)%></div>
      </div>
      <div class="col-4">
        <div class="p-2 mt-1"><%= campaign.date_created %> </div>
      </div>
      <div class="col-3">
        <div class="p-2 mt-1">
          <% if campaign.forms.empty? %>
            <%= link_to 'Create Form', new_campaign_form_path(campaign) %>
          <% else %>
            <%= link_to 'View Form', campaign_form_path(campaign.name, campaign.forms.first.title) %>
          <% end %>
        </div>
      </div>
      <div class="col-2">
        <%= link_to "EDIT", edit_campaign_path(campaign), class: "btn btn-primary rounded-3 p-2" %>
        <button data-action="click->popup#show" class="btn btn-primary rounded-3 p-2" type="submit">VIEW</button>
      </div>
      <%# popup box %>
      <div class="popup-overlay" data-popup-target="popupContent">
        <div class="popup-content">

          <div>
            <button class="x-button" data-action="click->popup#close">x</button>
          </div>

          <div class="d-flex justify-content-center px-2 pt-4">
            <h1><%= campaign.name.titleize %></h1>
          </div>

          <%# <div class="ps-5 mt-3" style="font-size: 20px;">TOTAL LEADS: <u><b><%= campaign.leads.count</b></u></div> %>
          <%= link_to campaign_leads_path(campaign), style: "text-decoration: none; color: black;" do %>
            <div class="ps-5 mt-3" style="font-size: 20px;">
            <br>
              <!-- Assuming the value '<%= campaign.leads.count %>' is within a container -->
            <p>Total Leads: <span class="text-primary"><%= campaign.leads.count %></span></p>
              </div>
            <% end %>

          <div class="ps-5 mt-3" style="font-size: 20px;">Campaign Details:</div>
          <div class="campaign-details border border-dark ml-5 my-3 p-2"><%= campaign.details.capitalize %></div>
          <br>

            <div class="campaign-button d-flex justify-content-center justify justify-content-evenly">
              <%= link_to "View Leads", campaign_leads_path(campaign), class: "btn btn-primary btn-lg" %>
              <button type="submit" class="btn btn-primary btn-lg">Edit</button>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/campaigns/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Campaign</h1>
    <p>Please update the campaign details.</p>
  </div>

  <div class="row">
    <%= simple_form_for @campaign do |f| %>
      <%= f.input :name %>

      <div class="row">
        <div class="col-md-6 mb-4">
          <%= f.input :start_date, as: :string, input_html: { readonly: true, class: 'form-control m-2 mb-3', id: 'campaign_start_date' }, placeholder: 'Campaign start date' %>
          <div id="inline_cal_from"></div>
        </div>
        <div class="col-md-6 mb-4">
          <%= f.input :end_date, as: :string, input_html: { readonly: true, class: 'form-control m-2 mb-3', id: 'campaign_end_date' }, placeholder: 'Campaign end date' %>
          <div id="inline_cal_to"></div>
        </div>
      </div>

      <%= f.input :details %>
      <div class="d-inline-flex">
        <%= f.submit "Next", class: "btn btn-primary button-next-cancel" %>
      <div>
    <% end %>

    <%= button_to "Cancel", campaigns_path, method: :get, class: "btn btn-light button-next-cancel" %>

  </div>
</div>

<script src="/rome.js"></script>
<script src="/jquery-3.3.1.min.js"></script>
<script src="/main.js"></script>

app/views/campaigns/index.html.erb
<div class="container">
  <h1 class="text-center my-5">Campaigns</h1>

  <div class="d-flex col-auto">
    <i class="fa-solid fa-magnifying-glass p-2 m-1 opacity-25"></i>
    <div data-controller="search-campaigns" style="width: 1000px;">
      <%= form_with url: campaigns_path, method: :get, html: {class:
        "mb-4", data: {search_campaigns_target: "form"}} do |f| %>
        <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search..",
                        value: params[:query],
                        data:
                        {search_campaigns_target: "input",
                          action: "keyup->search-campaigns#update"
                      } %>
        <% end %>
    </div>
  </div>

  <div class="container">
    <div class="row g-2">
      <div class="col-3">
        <div class="p-2 fs-5">Campaign Name</div>
      </div>
      <div class="col-4">
        <div class="p-2 fs-5">Date Created</div>
      </div>
      <div class="col-3">
        <div class="p-2 fs-5">URL</div>
      </div>
      <div class="col-2">
        <div class="p-2 fs-5">Actions</div>
      </div>
    </div>
  </div>

  <div class="box overflow-auto p-3 shadow-sm box-height">
      <%= render "campaign", campaigns: @campaigns %>
  </div>
</div>

<div class="text-center">
  <%# <%= link_to "Create New", new_campaign_path, class: " text-center btn btn-primary bottom-buttons" %>
  <%# <button class="mt-4 text-center btn btn-primary bottom-buttons" type="submit">Create New</button> %>
  <%= link_to "Create New", new_campaign_path, class: "mt-4 btn btn-primary bottom-buttons pt-4" %>
</div>

app/views/campaigns/new.html.erb
<%# Main container   %>
<div class="container">
  <div class="row">
    <h1>Create a new campaign</h1>
    <p>Please input campaign name, start date, end date, and details.</p>
  </div>

  <div class="row">
  <%# Simple form here %>
    <%= simple_form_for @campaign do |f| %>
      <%= f.input :name %>

      <div class="row">
        <div class="col-md-6 mb-4">
          <input name="campaign[start_date]" type="text" class="form-control m-2  mb-3" id="campaign_start_date" placeholder="Campaign start date" readonly>
          <div id="inline_cal_from"></div>
        </div>
        <div class="col-md-6 mb-4">
          <input name="campaign[end_date]" type="text" class="form-control m-2  mb-3" id="campaign_end_date" placeholder="Campaign end date" readonly>
          <div id="inline_cal_to"></div>
        </div>
      </div>

      <%= f.input :details %>

      <div class="d-inline-flex">
        <%= f.submit "Next", class: "btn btn-primary button-next-cancel" %>
      <div>
    <% end %>
    <%= button_to "Cancel", campaigns_path, method: :get, class: "btn btn-light button-next-cancel" %>
  </div>

</div>


<%# DO NOT TOUCH: Script of date picker %>
<script src="/rome.js"></script>
<script src="/jquery-3.3.1.min.js"></script>
<script src="/main.js"></script>

app/views/campaigns/show.html.erb
<div class="container border border-dark rounded-5 shadow-lg p-3 mb-5 mt-4">
  <div class="campaign-box border border-dark my-5">
    <div class="d-flex justify-content-center px-2 py-2">
      <h1><%= @campaign.name.upcase %></h1>
    </div>

    <% <div class="ps-5" style="font-size: 30px;">TOTAL LEADS: <u><b>=Lead.count</b></u></div> %>


    <div class="ps-5 mt-5" style="font-size: 30px;">CAMPAIGN DETAILS</div>
    <div class="border border-dark my-5 mx-5 shadow-lg p-3 mb-5"><%= @campaign.details.capitalize %></div>

  <div class="ps-5 pb-5">
    <div class="dates">
      <div class="start_date pb-5 d-flex align-items-center">
        <input class="form-control border-dark start_date me-3" type="text" placeholder="start date" style="border border-dark">
        <span class="fa fa-calendar start_date_calendar" aria-hidden="true "></span>
      </div>

      <div class="end_date pb-5 d-flex align-items-center  pb-5 d-flex align-items-center">
        <input class="form-control border-dark end_date me-3" type="text" placeholder="end date">
        <span class="fa fa-calendar end_date_calendar" aria-hidden="true "></span>
      </div>
    </div>

    <div class="campaign-button">
      <button type="submit" class="btn btn-primary btn-lg">EDIT</button>
    </div>
  </div>
</div>



<script src="https://cdn.jsdelivr.net/npm/@simondmc/popup-js@1.4.0/popup.min.js"></script>